apiVersion: v1
kind: Service
metadata:
  name: nosql-data
spec:
  selector:
    app: nosql-data
  ports:
    - port: 27017
      targetPort: http
      protocol: TCP
      name: http
  type: ClusterIP