# to expose the port in order to connect to the admin dashboard.

kind: Service
apiVersion: v1
metadata:
  name: rabbitmq-admin
spec:
  type: NodePort
  selector:
    app: rabbitmq
  ports:
    - port: 15672
      nodePort: 31672
      name: rabbitmq-port