version: '3.4'

services:
  duber.invoice.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=${APP_ENVIRONMENT:-Development}
      - ConnectionStrings__InvoiceDB=${AZURE_INVOICE_DB:-Server=sql.data;Database=Duber.InvoiceDb;User Id=sa;Password=Pass@word}      
      - EventBusConnection=${AZURE_SERVICE_BUS:-rabbitmq}
      - EventBusConnectionHC=${AZURE_SERVICE_BUS:-rabbitmq}
      - PaymentServiceBaseUrl=${PAYMENT_SERVICE_URL:-http://externalsystem.payment}
      - AzureServiceBusEnabled=${SERVICE_BUS_ENABLED:-False}
    ports:
      - "32776:80"

  duber.trip.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=${APP_ENVIRONMENT:-Development}
      - EventStoreConfiguration__ConnectionString=${AZURE_TRIP_DB:-mongodb://nosql.data}
      - EventBusConnection=${AZURE_SERVICE_BUS:-rabbitmq}
      - EventBusConnectionHC=${AZURE_SERVICE_BUS:-rabbitmq}
      - AzureServiceBusEnabled=${SERVICE_BUS_ENABLED:-False}
    ports:
      - "32775:80"

  duber.website:
    environment:
      - ASPNETCORE_ENVIRONMENT=${APP_ENVIRONMENT:-Development}
      - ConnectionStrings__WebsiteDB=${AZURE_WEBSITE_DB:-Server=sql.data;Database=Duber.WebSiteDb;User Id=sa;Password=Pass@word}      
      - EventBusConnection=${AZURE_SERVICE_BUS:-rabbitmq}
      - EventBusConnectionHC=${AZURE_SERVICE_BUS:-rabbitmq}
      - InvoiceApiSettings__BaseUrl=${INVOICE_SERVICE_BASE_URL:-http://duber.invoice.api}
      - TripApiSettings__BaseUrl=${TRIP_SERVICE_BASE_URL:-http://duber.trip.api}
      - TripApiSettings__NotificationsServerUrl=${NOTIFICATIONS_SERVER_URL:-http://duber.trip.notifications}
      - TripApiSettings__NotificationsClientUrl=${NOTIFICATIONS_CLIENT_URL:-http://docker.for.win.localhost:32778} #docker.for.mac.localhost / docker.for.linux.localhost (you could use the .env file to set this in a common variable, then use it here, i.e: LOCAL_DOMAIN=http://docker.for.win.localhost)
      - AzureServiceBusEnabled=${SERVICE_BUS_ENABLED:-False}
      - HealthChecksUI__HealthChecks__0__Name=Invoice HTTP Check
      - HealthChecksUI__HealthChecks__0__Uri=http://duber.invoice.api/readiness
      - HealthChecksUI__HealthChecks__1__Name=Trip HTTP Check
      - HealthChecksUI__HealthChecks__1__Uri=http://duber.trip.api/readiness
      - HealthChecksUI__HealthChecks__2__Name=Notifications HTTP Check
      - HealthChecksUI__HealthChecks__2__Uri=http://duber.trip.notifications/readiness
      - HealthChecksUI__HealthChecks__3__Name=Frontend HTTP Check
      - HealthChecksUI__HealthChecks__3__Uri=http://duber.website/readiness
    ports:
      - "32774:80"

  sql.data:
    environment:
      - MSSQL_SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
    ports:
      - "5433:1433"

  nosql.data:
    ports:
      - "27017:27017"

  externalsystem.payment:
    environment:
      - ASPNETCORE_ENVIRONMENT=${APP_ENVIRONMENT:-Development}
    ports:
      - "32777:80"

  duber.trip.notifications:
    environment:
      - ASPNETCORE_ENVIRONMENT=${APP_ENVIRONMENT:-Development}
      - ConnectionStrings__SignalrBackPlane=${REDIS_DB:-}
      - EventBusConnection=${AZURE_SERVICE_BUS:-rabbitmq}
      - EventBusConnectionHC=${AZURE_SERVICE_BUS:-rabbitmq}
      - AzureServiceBusEnabled=${SERVICE_BUS_ENABLED:-False}
    ports:
      - "32778:80"