apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: frontend
spec:
  rules:
  - host: duber.local.com
    http:
      paths:
      - path: /
        backend:
          serviceName: frontend
          servicePort: 80