apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: invoice
spec:
  rules:
  - host: invoice.local.com
    http:
      paths:
      - path: /
        backend:
          serviceName: invoice
          servicePort: 80