apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
spec:
  selector:
      matchLabels:
        app: payment
  replicas: 1
  template:
      metadata:
        labels:
            app: payment
      spec:
        containers:
        - name: payment
          image: vany0114/externalsystem.paymentservice
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: env-config
          ports:
          - containerPort: 80