apiVersion: apps/v1
kind: Deployment
metadata:
  name: sql-data
spec:
  selector:
      matchLabels:
        app: sql-data
  replicas: 1
  template:
      metadata:
        labels:
            app: sql-data
      spec:
        containers:
        - name: sql-data
          image: microsoft/mssql-server-linux:2017-latest
          imagePullPolicy: IfNotPresent          
          env:
          - name: ACCEPT_EULA
            value: "Y"
          - name: MSSQL_PID
            value: Developer
          - name: MSSQL_SA_PASSWORD
            value: Pass@word
          ports:
            - name: http
              containerPort: 1433
              protocol: TCP