apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: trip
spec:
  rules:
  - host: trip.local.com
    http:
      paths:
      - path: /
        backend:
          serviceName: trip
          servicePort: 80