apiVersion: apps/v1
kind: Deployment
metadata:
  name: trip
spec:
  selector:
      matchLabels:
        app: trip
  replicas: 1
  template:
      metadata:
        labels:
            app: trip
      spec:
        containers:
        - name: trip
          image: vany0114/duber.trip.api
          imagePullPolicy: Always
          resources:
            requests:
              memory: "128Mi"
              cpu: "200m"
            limits:
              memory: "256Mi"
              cpu: "600m"
          envFrom:
            - configMapRef:
                name: env-config
          livenessProbe:
            httpGet:
              port: 80
              path: /liveness
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readiness
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 60
            timeoutSeconds: 5
          ports:
          - containerPort: 80